const mechanisms = [
  {date:'2017-05-08',name:'Learned absolute positions',family:'position',problem:'Parallel sequence models need an explicit notion of order.',summary:'A trainable vector for each slot is added to the token embedding.',buys:'Flexible, simple, and strong inside the trained position range.',costs:'A fixed table creates a hard length boundary; unseen positions have no trained vector.',pick:'Fixed, modest input lengths where extrapolation is irrelevant.',source:'https://arxiv.org/abs/1705.03122',sourceTitle:'Convolutional Sequence to Sequence Learning',detail:'ConvS2S added learned position embeddings to input word embeddings so its parallel convolutional model could know which part of a sequence it was processing. The Transformer later compared learned positions with its fixed sinusoidal encoding.'},
  {date:'2017-06-12',name:'Scaled dot-product attention',family:'exact',problem:'Replace recurrence with parallel, content-based lookup.',summary:'Every query scores every key; softmax turns the scores into a weighted read from values.',buys:'Exact global lookup, parallel training, expressive multi-head specialization.',costs:'Quadratic score work; autoregressive serving stores every layer’s K and V.',pick:'Short-to-medium context where recall quality matters.',source:'https://arxiv.org/abs/1706.03762',sourceTitle:'Attention Is All You Need',detail:'The Transformer’s core operation. Scaling by √dₖ stabilizes dot products; multiple heads learn different subspaces. “Exact” means the usual dense softmax result, not perfect semantic recall.'},
  {date:'2017-06-12',name:'Sinusoidal positions',family:'position',problem:'Attention alone has no notion of order.',summary:'Fixed sine/cosine waves of different frequencies are added to token representations.',buys:'No learned position table; positions can be generated beyond training length.',costs:'Extrapolation is not guaranteed; additive signals can be awkward for relative distance.',pick:'A simple, parameter-free baseline or controlled extrapolation studies.',source:'https://arxiv.org/abs/1706.03762',sourceTitle:'Attention Is All You Need',detail:'The original Transformer used fixed sinusoidal encodings and reported nearly identical results with learned positional embeddings. Being mathematically defined outside the training range does not mean the model learned to use unseen ranges.'},
  {date:'2019-04-23',name:'Sparse attention',family:'sparse',problem:'Dense n² attention makes very long sequences impractical.',summary:'Compute only fixed local and strided patterns instead of the whole attention matrix.',buys:'Subquadratic O(n√n) attention and dramatically longer sequences.',costs:'The pattern can miss useful pairs; custom sparse kernels determine real speed.',pick:'Long structured inputs with predictable locality and occasional global hops.',source:'https://arxiv.org/abs/1904.10509',sourceTitle:'Generating Long Sequences with Sparse Transformers',detail:'Sparse Transformer factorized the attention matrix into local and strided patterns. Its million-step claim demonstrated feasibility in principle—not a general-purpose million-token language model.'},
  {date:'2019-11-06',name:'Multi-query attention · MQA',family:'cache',problem:'Incremental decoding is bottlenecked by repeatedly loading K/V cache.',summary:'Keep many query heads but share one K head and one V head across all of them.',buys:'A much smaller KV cache and less memory bandwidth during decoding.',costs:'One shared KV representation can reduce quality and limits head-wise diversity.',pick:'High-throughput serving where memory bandwidth dominates.',source:'https://arxiv.org/abs/1911.02150',sourceTitle:'Fast Transformer Decoding: One Write-Head is All You Need',detail:'MQA changes neither the dense attention span nor its prefill asymptotics. Its big win is the amount of cached K/V data read for each generated token.'},
  {date:'2020-03-12',name:'Content-routed / top-k sparse',family:'sparse',problem:'Fixed sparse patterns cannot know which distant token matters.',summary:'Route similar queries and keys together, then attend within selected clusters or top-k candidates.',buys:'Content-dependent global reach at subquadratic cost.',costs:'Selection itself costs compute; routing errors silently hide relevant evidence.',pick:'Long contexts whose important links are non-local but semantically clusterable.',source:'https://arxiv.org/abs/2003.05997',sourceTitle:'Efficient Content-Based Sparse Attention with Routing Transformers',detail:'Routing Transformer is a canonical content-based sparse milestone. Later learned indexers, including DeepSeek DSA, perform a finer token-level form of selection.'},
  {date:'2020-04-10',name:'Sliding-window attention',family:'sparse',problem:'Most dependencies are local; why pay to look everywhere?',summary:'Each token attends only within a fixed neighborhood, sometimes with a few global tokens.',buys:'Linear compute in sequence length and bounded local KV memory.',costs:'Information outside the window disappears or needs many layers to propagate.',pick:'Streaming, local structure, or long documents with known global anchor tokens.',source:'https://arxiv.org/abs/2004.05150',sourceTitle:'Longformer: The Long-Document Transformer',detail:'Local attention appeared earlier in several forms; this card dates the canonical Longformer formulation that combines a sliding window with task-motivated global attention.'},
  {date:'2020-06-29',name:'Linear attention',family:'linear',problem:'Remove the quadratic attention matrix altogether.',summary:'Use a kernel feature map and reassociate products: φ(Q)(φ(K)ᵀV).',buys:'Linear-time sequence processing; recurrent decoding with fixed-size state.',costs:'Not softmax attention; finite state can collide, blur, and lose exact retrieval.',pick:'Very long or streaming workloads where bounded state matters more than exact recall.',source:'https://arxiv.org/abs/2006.16236',sourceTitle:'Transformers are RNNs',detail:'Reordering multiplication avoids materializing QKᵀ. Causal linear attention becomes a recurrent update, but the compressed state has finite capacity.'},
  {date:'2021-02-22',name:'The delta rule',family:'linear',problem:'Additive linear memory cannot overwrite a key cleanly.',summary:'Read the old value for a key, subtract the error, then write the corrected association.',buys:'More precise fast-weight updates and better associative recall than additive state.',costs:'Still finite-capacity memory; the original sequential update was hard to parallelize.',pick:'Recurrent linear models that need editable key→value memory.',source:'https://arxiv.org/abs/2102.11174',sourceTitle:'Linear Transformers Are Secretly Fast Weight Programmers',detail:'The delta rule itself is older neural-memory work. This date marks its modern linear-attention formulation: update memory using the difference between the desired value and current readout.'},
  {date:'2021-04-20',name:'RoPE',family:'position',problem:'Encode relative distance without adding a separate bias table.',summary:'Rotate Q and K vector pairs by position-dependent angles before their dot product.',buys:'Relative offsets emerge in Q·K; no absolute lookup table; efficient in practice.',costs:'High-frequency rotations break beyond training length; scaling needs care.',pick:'The modern default for decoder LLMs at trained context lengths.',source:'https://arxiv.org/abs/2104.09864',sourceTitle:'RoFormer: Enhanced Transformer with Rotary Position Embedding',detail:'RoPE encodes absolute position through rotations while making the inner product depend on relative displacement. It became ubiquitous—but raw RoPE does not reliably extrapolate far.'},
  {date:'2021-08-27',name:'ALiBi',family:'position',problem:'Train short, then run longer without position embeddings.',summary:'Add a head-specific linear distance penalty directly to attention logits.',buys:'Tiny overhead, strong recency prior, and useful length extrapolation.',costs:'Distance is only a monotonic penalty; far evidence is structurally discouraged.',pick:'Models trained from scratch for simple, robust extrapolation and recency-heavy tasks.',source:'https://arxiv.org/abs/2108.12409',sourceTitle:'Train Short, Test Long: Attention with Linear Biases',detail:'Different heads receive different penalty slopes, leaving some heads more able to look far back. ALiBi changes position bias, not dense attention’s quadratic compute.'},
  {date:'2022-05-27',name:'FlashAttention',family:'exact',problem:'Exact attention is often memory-IO bound, not arithmetic bound.',summary:'Tile Q, K and V through fast SRAM and recompute online softmax without storing the n² matrix.',buys:'Exact outputs, lower memory traffic, faster training, linear auxiliary memory.',costs:'Dense arithmetic remains quadratic; speed depends on hardware-aware kernels.',pick:'Almost any dense-attention model on supported accelerators.',source:'https://arxiv.org/abs/2205.14135',sourceTitle:'FlashAttention: Fast and Memory-Efficient Exact Attention',detail:'FlashAttention is an algorithm, not a new learned attention pattern. It preserves exact dense attention (up to numerical precision) while changing the IO schedule.'},
  {date:'2023-05-22',name:'Grouped-query attention · GQA',family:'cache',problem:'MQA saves memory but compresses all KV heads into one.',summary:'Share each KV head across a group of query heads—the middle ground between MHA and MQA.',buys:'Near-MQA serving speed and cache savings with quality closer to MHA.',costs:'Still loses some KV diversity; grouping and tensor parallelism need tuning.',pick:'General-purpose LLM serving—the pragmatic default compromise.',source:'https://arxiv.org/abs/2305.13245',sourceTitle:'GQA: Training Generalized Multi-Query Transformer Models',detail:'GQA also introduced an uptraining recipe to convert MHA checkpoints using 5% of original pretraining compute. One KV group equals MQA; one per query head equals MHA.'},
  {date:'2023-06-28',name:'NTK-aware RoPE scaling',family:'position',problem:'Extend a RoPE model without crushing every frequency equally.',summary:'Increase RoPE’s base so low frequencies stretch more while high frequencies preserve local resolution.',buys:'Useful zero-shot context extension with a tiny inference-time change.',costs:'Community-born heuristic; quality can degrade or collapse near the new limit.',pick:'Quick experiments or compatibility extensions when retraining is unavailable.',source:'https://www.reddit.com/r/LocalLLaMA/comments/14lz7j5/ntkaware_scaled_rope_allows_llama_models_to_have/',sourceTitle:'Original bloc97 LocalLLaMA post',detail:'Unlike most entries, this did not begin as a paper. The original public post is dated 28 June 2023; subsequent dynamic-NTK variants and library implementations followed. Attribution uncertainty is stated rather than papered over.'},
  {date:'2023-08-31',name:'YaRN',family:'position',problem:'RoPE scaling needs both frequency correction and stable attention magnitude.',summary:'Blend interpolation and extrapolation across frequencies, then add temperature scaling.',buys:'Efficient long-context fine-tuning; strong extension with relatively little data.',costs:'More hyperparameters; still requires validation and usually long-context fine-tuning.',pick:'Extending an existing RoPE checkpoint to a planned longer context.',source:'https://arxiv.org/abs/2309.00071',sourceTitle:'YaRN: Efficient Context Window Extension of LLMs',detail:'YaRN combines “NTK-by-parts” frequency treatment with an attention magnitude correction. It reported 10× fewer tokens and 2.5× fewer steps than prior extension methods.'},
  {date:'2023-09-29',name:'Attention sinks',family:'cache',problem:'A rolling KV window collapses after early tokens are evicted.',summary:'Keep a few initial sink tokens plus the recent window, even if the sinks carry little semantics.',buys:'Stable streaming for millions of processed tokens with fixed KV memory.',costs:'Not true infinite memory; content outside the window is forgotten.',pick:'Endless chat or streams where local continuity matters more than old facts.',source:'https://arxiv.org/abs/2309.17453',sourceTitle:'Efficient Streaming Language Models with Attention Sinks',detail:'StreamingLLM showed that keeping initial KVs restores windowed performance. “4M tokens” describes stable processing, not the ability to retrieve arbitrary facts from 4M tokens ago.'},
  {date:'2024-05-07',name:'Multi-head latent attention · MLA',family:'cache',problem:'At long context, even GQA’s KV cache is painfully large.',summary:'Compress K/V into a shared low-rank latent; reconstruct per-head components when needed.',buys:'Very large KV-cache reduction while retaining richer head-specific attention.',costs:'Complex projections and RoPE decoupling; specialized kernels are important.',pick:'Large-scale serving where KV capacity and bandwidth dominate cost.',source:'https://arxiv.org/abs/2405.04434',sourceTitle:'DeepSeek-V2 Technical Report',detail:'DeepSeek-V2 reported a 93.3% KV-cache reduction versus its comparison baseline. MLA is cache compression; it does not make dense attention subquadratic by itself.'},
  {date:'2024-06-10',name:'Parallel DeltaNet',family:'linear',problem:'The delta rule remembered better but trained sequentially.',summary:'A chunkwise algorithm parallelizes delta-rule memory updates across sequence length.',buys:'Hardware-efficient training with stronger associative recall than basic linear attention.',costs:'Complex scan math; finite recurrent state still trails exact attention on some retrieval.',pick:'Linear-time backbones or hybrids that need editable memory at scale.',source:'https://arxiv.org/abs/2406.06484',sourceTitle:'Parallelizing Linear Transformers with the Delta Rule',detail:'This work made DeltaNet practical at 1.3B scale and found hybrids with sliding-window or global attention stronger than pure alternatives—a revealing vote for mixed systems.'},
  {date:'2024-12-09',name:'Gated DeltaNet',family:'linear',problem:'Delta updates can correct memory but cannot rapidly clear obsolete state.',summary:'Add data-dependent decay: gating erases broadly; the delta rule edits precisely.',buys:'Better memory control, retrieval, and length extrapolation with linear recurrence.',costs:'More complex recurrence and kernels; fixed-size state remains a lossy bottleneck.',pick:'Long streaming models, especially hybridized with occasional exact attention.',source:'https://arxiv.org/abs/2412.06464',sourceTitle:'Gated Delta Networks: Improving Mamba2 with Delta Rule',detail:'The two controls are complementary: decay forgets, delta updates correct. The authors’ best hybrids retain sliding-window attention or Mamba2 layers.'},
  {date:'2025-02-16',name:'Native Sparse Attention · NSA',family:'sparse',problem:'Sparse ideas often look efficient on paper but run poorly on GPUs.',summary:'Combine compressed global blocks, selected fine-grained blocks, and a local window in a hardware-aligned design.',buys:'Global overview + chosen detail + locality; trainable end-to-end with real 64K speedups.',costs:'Three branches and custom kernels; compression/selection can discard evidence.',pick:'Training long-context models from scratch on supported accelerator stacks.',source:'https://arxiv.org/abs/2502.11089',sourceTitle:'Native Sparse Attention',detail:'This is DeepSeek’s “compressed and sparse” three-branch mechanism: coarse compression, fine selection, and sliding attention. It should not be conflated with the later DSA indexer.'},
  {date:'2025-09-29',name:'DeepSeek Sparse Attention · DSA',family:'sparse',problem:'Dense MLA still scores every past latent at long context.',summary:'A small FP8 lightning indexer ranks past tokens; full MLA attends only to the top-k selected cache entries.',buys:'Fine-grained token sparsity and much lower long-context training/inference cost.',costs:'Indexer overhead and recall risk; specialized sparse kernels are required.',pick:'Long-context MLA models with training budget to learn a reliable selector.',source:'https://api-docs.deepseek.com/news/news250929/',sourceTitle:'DeepSeek-V3.2-Exp official release',detail:'V3.2-Exp introduced DSA through continued training from V3.1-Terminus. It uses a learned lightning indexer plus token-level top-k—not NSA’s three parallel branches.'},
  {date:'2025-12-13',name:'DroPE',family:'position',problem:'Position encodings help training, then become the extrapolation bottleneck.',summary:'Remove positional embeddings after pretraining and briefly recalibrate the model.',buys:'Zero-shot extension after a short adaptation; preserves original-range ability in reported tests.',costs:'Requires model surgery and recalibration; evidence is new and scale coverage limited.',pick:'Researching post-training extension when RoPE scaling remains brittle.',source:'https://arxiv.org/abs/2512.12167',sourceTitle:'Extending the Context of Pretrained LLMs by Dropping Their Positional Embeddings',detail:'DroPE is dated December 2025—not 2024. It argues position is a useful training scaffold but an inference-time extrapolation constraint. Results should be treated as promising, recent evidence.'}
];

const familyLabels={exact:'Exact attention',position:'Position',sparse:'Sparse',cache:'KV memory',linear:'Linear state'};
const familyColors={exact:'#5577ff',position:'#e9a53a',sparse:'#ff6948',cache:'#46a879',linear:'#8a66bd'};
const filters=['all','exact','position','sparse','cache','linear'];
const eraNotes={2017:'Make sequence modeling parallel.',2019:'The quadratic bill becomes visible.',2020:'Length: local, routed, or recurrent?',2021:'Memory learns position—and how to edit.',2022:'Keep exactness. Fix the hardware path.',2023:'Serving memory and context extension collide.',2024:'Compress the cache; improve recurrent state.',2025:'Learn what to keep. Question position itself.'};
let activeFilter='all',searchQuery='';
const filterRoot=document.querySelector('#filters');
filters.forEach((f,i)=>{const b=document.createElement('button');b.className='filter'+(i===0?' active':'');b.textContent=f==='all'?'All mechanisms':familyLabels[f];b.dataset.filter=f;b.onclick=()=>{activeFilter=f;document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderTimeline()};filterRoot.appendChild(b)});

function miniPattern(family,idx){let on=[];for(let r=0;r<5;r++)for(let c=0;c<8;c++){if(family==='exact'||(family==='position'&&(r+c)%3!==0)||family==='sparse'&&(Math.abs(c-r-1)<2||c===0||(r*3+c)%11===0)||family==='cache'&&(c<3||c===7)||family==='linear'&&(c===r||c===r+1||c===0))on.push(r*8+c)}return `<div class="mini-viz" style="--viz:${familyColors[family]}">${Array.from({length:40},(_,i)=>`<i class="${on.includes(i)?'on':''}" style="opacity:${on.includes(i)?.45+((i+idx)%5)/8:1}"></i>`).join('')}</div>`}
function renderTimeline(){
 const root=document.querySelector('#timelineList');root.innerHTML='';
 const q=searchQuery.toLowerCase();
 const shown=mechanisms.filter(m=>(activeFilter==='all'||m.family===activeFilter)&&(!q||Object.values(m).some(v=>String(v).toLowerCase().includes(q))));
 document.querySelector('#resultCount').textContent=`Showing ${shown.length} of ${mechanisms.length} mechanisms${q?` for “${searchQuery}”`:''}`;
 if(!shown.length){root.innerHTML='<div class="empty-results">No mechanism matches that search. Try “cache”, “streaming”, or “RoPE”.</div>';return}
 const years=[...new Set(shown.map(m=>m.date.slice(0,4)))];
 years.forEach(year=>{const era=document.createElement('section');era.className='era';const list=shown.filter(m=>m.date.startsWith(year));era.innerHTML=`<div class="era-year-wrap"><div class="era-year">${year}</div><p class="era-note">${eraNotes[year]}</p></div><div class="cards">${list.map((m,i)=>`<article class="mechanism-card" style="--viz:${familyColors[m.family]}"><div class="card-top"><span class="date">${new Date(m.date+'T00:00:00').toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'})}</span><span class="family ${m.family}">${familyLabels[m.family]}</span></div><h3>${m.name}</h3><p class="problem">The bill: ${m.problem}</p><p class="summary">${m.summary}</p>${miniPattern(m.family,i)}<div class="trade-row"><div class="buys"><b>BUYS</b>${m.buys}</div><div class="costs"><b>GIVES UP</b>${m.costs}</div></div><div class="card-action"><span class="pick">Pick it: ${m.pick}</span><div class="card-buttons"><button class="compare-add ${compareSelection.includes(m.name)?'selected':''}" data-name="${m.name.replaceAll('"','&quot;')}">${compareSelection.includes(m.name)?'✓ Added':'+ Compare'}</button><button class="learn-more" data-name="${m.name.replaceAll('"','&quot;')}">Details →</button></div></div></article>`).join('')}</div>`;root.appendChild(era)});
 document.querySelectorAll('.learn-more').forEach(b=>b.onclick=()=>openDetail(mechanisms.find(m=>m.name===b.dataset.name)));
 document.querySelectorAll('.compare-add').forEach(b=>b.onclick=()=>toggleCompare(b.dataset.name));
}
const timelineSearch=document.querySelector('#timelineSearch');
timelineSearch.oninput=()=>{searchQuery=timelineSearch.value.trim();renderTimeline()};
let compareSelection=[];
renderTimeline();

const dialog=document.querySelector('#detailDialog'),dialogContent=document.querySelector('#dialogContent');
function openDetail(m){dialogContent.innerHTML=`<div class="dialog-body"><p class="eyebrow">${m.date} · ${familyLabels[m.family]}</p><h2>${m.name}</h2><p class="one-line">${m.summary}</p><div class="dialog-section"><h4>THE HISTORICAL ANSWER</h4><p>${m.detail}</p></div><div class="dialog-section"><h4>THE HONEST TRADE</h4><p><b>It buys:</b> ${m.buys}</p><p><b>It gives up:</b> ${m.costs}</p><p><b>Actually pick it for:</b> ${m.pick}</p></div><a class="source-link" href="${m.source}" target="_blank" rel="noreferrer">Read the primary source: ${m.sourceTitle} ↗</a></div>`;dialog.showModal()}
document.querySelector('.dialog-close').onclick=()=>dialog.close();dialog.onclick=e=>{if(e.target===dialog)dialog.close()};

function toggleCompare(name){
 const index=compareSelection.indexOf(name);
 if(index>=0)compareSelection.splice(index,1);
 else if(compareSelection.length<2)compareSelection.push(name);
 else compareSelection=[compareSelection[1],name];
 updateCompareTray();renderTimeline();
}
function updateCompareTray(){
 const tray=document.querySelector('#compareTray');tray.classList.toggle('visible',compareSelection.length>0);
 document.querySelector('#comparePicks').innerHTML=compareSelection.map(name=>`<span class="compare-pick">${name}<button data-remove="${name.replaceAll('"','&quot;')}" aria-label="Remove ${name}">×</button></span>`).join('');
 document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>toggleCompare(b.dataset.remove));
 document.querySelector('#runComparison').disabled=compareSelection.length!==2;
}
document.querySelector('#runComparison').onclick=()=>{
 const picked=compareSelection.map(name=>mechanisms.find(m=>m.name===name));
 dialogContent.innerHTML=`<div class="dialog-body"><p class="eyebrow">HEAD TO HEAD</p><h2>What are you willing to lose?</h2><div class="comparison-grid">${picked.map(m=>`<div class="comparison-col"><small>${m.date} · ${familyLabels[m.family]}</small><h3>${m.name}</h3><dl><dt>THE MOVE</dt><dd>${m.summary}</dd><dt>BUYS</dt><dd>${m.buys}</dd><dt>GIVES UP</dt><dd>${m.costs}</dd><dt>PICK IT WHEN</dt><dd>${m.pick}</dd></dl><a class="source-link" href="${m.source}" target="_blank" rel="noreferrer">Primary source ↗</a></div>`).join('')}</div></div>`;
 dialog.showModal();
};

const memoryConfigs={
 MHA:{label:'MHA',kvHeads:32,color:'#5577ff',explanation:'Every query head owns a K and a V head. Maximum head-wise diversity, maximum cache: the serving baseline.'},
 MQA:{label:'MQA',kvHeads:1,color:'#ff6948',explanation:'All 32 query heads share one K/V pair. The cache collapses dramatically, but so does KV-head diversity.'},
 GQA:{label:'GQA',kvHeads:8,color:'#46a879',explanation:'Eight K/V heads each serve four query heads. This middle ground is why GQA became a practical serving default.'},
 MLA:{label:'MLA',kvHeads:.5625,color:'#c8f05a',explanation:'A shared 512-d latent plus a small positional component stands in for per-head K/V. The diagram shows compression, not literal heads.'}
};
let memoryMethod='MHA';
const memoryLengths=[2048,8192,32768,131072,524288,1048576];
const methodRoot=document.querySelector('#memoryMethods');
Object.keys(memoryConfigs).forEach(key=>{const b=document.createElement('button');b.className='method-tab'+(key===memoryMethod?' active':'');b.textContent=key;b.onclick=()=>{memoryMethod=key;document.querySelectorAll('.method-tab').forEach(x=>x.classList.toggle('active',x===b));drawMemory()};methodRoot.appendChild(b)});
function formatBytes(bytes){const gib=bytes/1073741824;return gib>=1024?`${(gib/1024).toFixed(1)} TiB`:`${gib.toFixed(gib<10?1:0)} GiB`}
function drawMemory(){
 const index=+document.querySelector('#memoryContext').value,tokens=memoryLengths[index],config=memoryConfigs[memoryMethod];
 const baseline=32*tokens*2*32*128*2;
 const bytes=memoryMethod==='MLA'?32*tokens*576*2:32*tokens*2*config.kvHeads*128*2;
 document.querySelector('#memoryContextOut').value=tokens>=1048576?'1M tokens':`${tokens/1024}K tokens`;
 document.querySelector('#memorySize').textContent=formatBytes(bytes);
 document.querySelector('#memorySize').style.color=config.color;
 document.querySelector('#memorySaving').textContent=memoryMethod==='MHA'?'baseline':`${Math.round((1-bytes/baseline)*100)}% smaller than MHA`;
 document.querySelector('#memoryExplanation').textContent=config.explanation;
 const qHeads=Array.from({length:32},()=>'<i class="head"></i>').join('');
 let kvHeads;if(memoryMethod==='MLA')kvHeads='<i class="head latent"></i>';else kvHeads=Array.from({length:config.kvHeads},()=>'<i class="head kv"></i>').join('');
 document.querySelector('#headDiagram').innerHTML=`<div class="head-row"><span>Q ×32</span><div class="heads">${qHeads}</div></div><div class="head-row"><span>${memoryMethod==='MLA'?'latent':'K/V'}</span><div class="heads">${kvHeads}</div></div>`;
}
document.querySelector('#memoryContext').oninput=drawMemory;drawMemory();

const tokens=['The','cat','sat','on','the','warm','windowsill','.'];
const notes=['A determiner mostly needs its nearby noun.','The subject looks toward its action.','The verb gathers subject, place, and modifier.','A preposition binds the action to its object.','This determiner points forward to a noun.','The adjective modifies “windowsill”.','The place links back to “sat”.','The stop token summarizes the completed clause.'];
const logits=[[2.2,2.6,.5,.2,.1,.1,.2,-1],[.7,2.5,.8,.2,0,.1,.2,-1],[1.4,2.8,3.1,.6,.2,.2,.4,-1],[.2,.4,2.2,2.4,.7,.2,.4,-1],[0,.1,.3,.8,2.3,1.2,2,-1],[0,.2,.4,.3,.8,2.3,2.8,-1],[.2,.9,2.2,.7,.8,1.9,3,-.5],[.6,1.1,2.5,.5,.4,1.3,1.8,2.4]];
let query=2;const tokenRow=document.querySelector('#tokenRow');tokens.forEach((t,i)=>{const b=document.createElement('button');b.className='token'+(i===query?' active':'');b.textContent=t;b.onclick=()=>{query=i;document.querySelectorAll('.token').forEach((x,j)=>x.classList.toggle('active',j===i));drawAttention()};tokenRow.appendChild(b)});
function drawAttention(){const temp=+document.querySelector('#temperature').value;document.querySelector('#tempValue').value=temp.toFixed(2);const causal=document.querySelector('#causalToggle').checked;const raw=logits[query].map((v,i)=>causal&&i>query?-Infinity:v/temp);const max=Math.max(...raw);const ex=raw.map(v=>v===-Infinity?0:Math.exp(v-max));const sum=ex.reduce((a,b)=>a+b);const probs=ex.map(v=>v/sum);document.querySelector('#queryWord').textContent=tokens[query];document.querySelector('#queryNote').textContent=notes[query];document.querySelector('#attentionBars').innerHTML=probs.map((p,i)=>`<div class="attn-col"><small>${Math.round(p*100)}%</small><div class="attn-bar" style="height:${Math.max(2,p*155)}px;opacity:${p?(.35+p*.65):.1}"></div><span>${tokens[i]}</span></div>`).join('')}
document.querySelector('#temperature').oninput=drawAttention;document.querySelector('#causalToggle').onchange=drawAttention;drawAttention();

const lengths=[2,8,32,128,512,1000];const labels=['2K','8K','32K','128K','512K','1M'];
const costSeries=[{name:'Dense / Flash',color:'#5577ff',fn:n=>Math.min(100,4+96*(n*n)/(128*128))},{name:'Sliding window',color:'#ff6948',fn:n=>Math.min(100,3+n/18)},{name:'Sparse / top-k',color:'#46a879',fn:n=>Math.min(100,5+n/25)},{name:'Linear state',color:'#8a66bd',fn:n=>Math.min(100,3+n/80)}];
function drawCost(){const i=+document.querySelector('#contextSlider').value,n=lengths[i];document.querySelector('#contextOutput').value=labels[i];document.querySelector('#costChart').innerHTML=costSeries.map(s=>{const v=s.fn(n);return `<span class="chart-label">${s.name}</span><div class="chart-track"><div class="chart-bar" style="width:${v}%;background:${s.color}"></div></div><span class="chart-value">${v<15?'low':v<45?'mid':'high'}</span>`}).join('');const rec=i<2?'Dense FlashAttention + GQA is the safe default: exact, fast, and simple.':i<4?'Start with FlashAttention + GQA/MLA; use windows if the task is local, sparse attention if it is not.':'Extreme length forces a memory policy: learned sparsity for retrieval, or linear state for bounded streaming. Hybrid layers hedge the trade.';document.querySelector('#recommendationText').textContent=rec}
document.querySelector('#contextSlider').oninput=drawCost;drawCost();
document.documentElement.classList.add('reveal-ready');
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
function updateScrollProgress(){const max=document.documentElement.scrollHeight-innerHeight;document.querySelector('#scrollProgress').style.width=`${max>0?scrollY/max*100:0}%`}
addEventListener('scroll',updateScrollProgress,{passive:true});addEventListener('resize',updateScrollProgress);updateScrollProgress();
